version: '3.5'

services:
  db_informatica:
    container_name: db_informatica
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    image: postgres:15.2-alpine
    ports:
      - "5434:5432"
